version: '3.8'

services:
  dic-shell:
    build: .
    user: root
    volumes:
      - .:/app
    network_mode: "host"
    stdin_open: true
    tty: true
    environment:
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      AWS_DEFAULT_REGION: us-east-1
